"""drop all table

Revision ID: 13fbd46de3dd
Revises: 62373f8a677f
Create Date: 2022-05-05 07:43:39.841509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13fbd46de3dd'
down_revision = '62373f8a677f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
