"""adding status to order table

Revision ID: 2208a2cd7922
Revises: 42d62e54b69a
Create Date: 2022-05-07 07:36:12.051641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2208a2cd7922'
down_revision = '42d62e54b69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'states', ['state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'state_id')
    # ### end Alembic commands ###
