"""fixing bugs adding 2date 2time

Revision ID: 2de722b9b4ae
Revises: 29c6036d4238
Create Date: 2022-05-16 21:47:45.494236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2de722b9b4ae'
down_revision = '29c6036d4238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('tdate', sa.Date(), nullable=True))
    op.add_column('flights', sa.Column('adate', sa.Date(), nullable=True))
    op.add_column('flights', sa.Column('ttime', sa.Time(), nullable=True))
    op.add_column('flights', sa.Column('atime', sa.Time(), nullable=True))
    op.drop_column('flights', 'date')
    op.drop_column('tickets', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('flights', 'atime')
    op.drop_column('flights', 'ttime')
    op.drop_column('flights', 'adate')
    op.drop_column('flights', 'tdate')
    # ### end Alembic commands ###
