"""fixing bugs

Revision ID: 3a301b062aea
Revises: 2de722b9b4ae
Create Date: 2022-05-16 21:55:14.018760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a301b062aea'
down_revision = '2de722b9b4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'tdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('flights', 'adate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('flights', 'ttime',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('flights', 'atime',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'atime',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('flights', 'ttime',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('flights', 'adate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('flights', 'tdate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
