"""changing colomn/row to str/ add's

Revision ID: 3d6d7db3d3e6
Revises: c45374282041
Create Date: 2022-05-07 16:24:20.838023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6d7db3d3e6'
down_revision = 'c45374282041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('rows', sa.String(), nullable=False))
    op.add_column('seats', sa.Column('cols', sa.String(), nullable=False))
    op.drop_column('seats', 'row')
    op.drop_column('seats', 'col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('col', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seats', sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('seats', 'cols')
    op.drop_column('seats', 'rows')
    # ### end Alembic commands ###
