"""adding a class to waitlist table

Revision ID: 42d62e54b69a
Revises: 5caddebd55ae
Create Date: 2022-05-07 07:32:23.187680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d62e54b69a'
down_revision = '5caddebd55ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist', sa.Column('class_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'waitlist', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist', type_='foreignkey')
    op.drop_column('waitlist', 'class_id')
    # ### end Alembic commands ###
