"""missing something?

Revision ID: 476c76ff64a8
Revises: bf08b9d1b4dd
Create Date: 2022-05-02 01:49:04.143569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476c76ff64a8'
down_revision = 'bf08b9d1b4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Temp_user_fk', 'Temp', type_='foreignkey')
    op.drop_column('Temp', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Temp', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Temp_user_fk', 'Temp', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
