"""missing something?

Revision ID: 476c76ff64a8
Revises: bf08b9d1b4dd
Create Date: 2022-05-02 01:49:04.143569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476c76ff64a8'
down_revision = 'bf08b9d1b4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
