"""removing date from order table, it's by the flight and in flight table

Revision ID: 55d43dc842f4
Revises: 2208a2cd7922
Create Date: 2022-05-07 07:40:41.355988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d43dc842f4'
down_revision = '2208a2cd7922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
