"""changing cloumn to col

Revision ID: 590b58243281
Revises: 7ac4e31ebc1e
Create Date: 2022-05-07 16:15:34.542042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590b58243281'
down_revision = '7ac4e31ebc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('col', sa.String(), nullable=False))
    op.drop_column('seats', 'column')
    op.alter_column('seats', sa.Column('row', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('column', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('seats', 'col')
    op.alter_column('seats', sa.Column('row', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
