"""changin the name of Temp from Temp to post

Revision ID: 73177618ef56
Revises: 6a378d126df0
Create Date: 2022-05-02 02:49:53.263298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73177618ef56'
down_revision = '6a378d126df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
