"""changing user_id to owner_id

Revision ID: 741a6fed40d4
Revises: e847986c4d79
Create Date: 2022-05-02 01:54:37.794571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741a6fed40d4'
down_revision = 'e847986c4d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Temp', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('Temp_user_id_fkey', 'Temp', type_='foreignkey')
    op.create_foreign_key(None, 'Temp', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Temp', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Temp', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Temp', type_='foreignkey')
    op.create_foreign_key('Temp_user_id_fkey', 'Temp', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Temp', 'owner_id')
    # ### end Alembic commands ###
