"""changing colomn/row to str

Revision ID: 7ac4e31ebc1e
Revises: 409ae5692637
Create Date: 2022-05-07 16:12:58.351826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac4e31ebc1e'
down_revision = '409ae5692637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
