"""restricted ticket_id on Order table

Revision ID: 8357cdc981ad
Revises: bd9b4f018a27
Create Date: 2022-05-14 15:07:19.970407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8357cdc981ad'
down_revision = 'bd9b4f018a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ticket_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'tickets', ['ticket_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ticket_id_fkey', 'orders', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
