"""resetting the database

Revision ID: a5788758e804
Revises: 741a6fed40d4
Create Date: 2022-05-02 02:13:56.860140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5788758e804'
down_revision = '741a6fed40d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
