"""maintenance table: flight_id/key -> plane_id/key

Revision ID: bd9b4f018a27
Revises: 3d6d7db3d3e6
Create Date: 2022-05-07 17:33:29.826743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9b4f018a27'
down_revision = '3d6d7db3d3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintentaces', sa.Column('plane_id', sa.Integer(), nullable=False))
    op.drop_constraint('maintentaces_flight_id_fkey', 'maintentaces', type_='foreignkey')
    op.create_foreign_key(None, 'maintentaces', 'planes', ['plane_id'], ['id'], ondelete='CASCADE')
    op.drop_column('maintentaces', 'flight_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintentaces', sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'maintentaces', type_='foreignkey')
    op.create_foreign_key('maintentaces_flight_id_fkey', 'maintentaces', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    op.drop_column('maintentaces', 'plane_id')
    # ### end Alembic commands ###
