"""updating fines table with amount

Revision ID: cc6233b78eba
Revises: 026bbc663549
Create Date: 2022-05-07 04:26:28.462927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6233b78eba'
down_revision = '026bbc663549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fines', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fines', 'amount')
    # ### end Alembic commands ###
