"""adding phone number + owner_id

Revision ID: e847986c4d79
Revises: 476c76ff64a8
Create Date: 2022-05-02 01:53:21.068011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e847986c4d79'
down_revision = '476c76ff64a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Temp', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Temp', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'Temp', type_='foreignkey')
    op.drop_column('Temp', 'user_id')
    # ### end Alembic commands ###
